//! Every file the installer writes into the target system, in one place.
//!
//! Shell scripts (rollback, rescue-sync, mirror optimizer), dinit service
//! definitions, dotfile templates (zsh/fish/kitty), desktop-session entries,
//! pacman hooks, the Secure Boot README, and compile-time embedded assets
//! (waybar/wofi/fastfetch configs, the Pinnacle config tarball).
//!
//! Editing rules: scripts are POSIX sh unless the shebang says otherwise —
//! check with `dash -n`; text destined for `format!` escapes braces or uses
//! @@PLACEHOLDER@@; `include_str!`/`include_bytes!` paths are relative to
//! THIS file (`../../assets/...`).

/// .zshrc shipped to the user when they pick zsh. Mirrors a typical oh-my-zsh
/// feature set using the distro's plugin packages, then starts starship.
pub(crate) const ZSHRC_TEMPLATE: &str = r#"# ~/.zshrc — generated by the Artix installer

# History
HISTFILE=~/.zsh_history
HISTSIZE=50000
SAVEHIST=50000
setopt SHARE_HISTORY HIST_IGNORE_ALL_DUPS HIST_IGNORE_SPACE INC_APPEND_HISTORY

# Completion system
autoload -Uz compinit && compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
setopt AUTO_CD
# Treat '#' as a comment on the interactive prompt too, so pasted commands
# with trailing comments don't error out (off by default in zsh).
setopt INTERACTIVE_COMMENTS

# Plugins (installed from the repos)
[ -f /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ] && \
  source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
[ -f /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh ] && \
  source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
# Syntax highlighting must be sourced last.
[ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && \
  source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# History substring search: bind up/down arrows
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Handy aliases
alias ls='ls --color=auto'
alias ll='ls -lah'
alias grep='grep --color=auto'
alias ..='cd ..'

# Starship prompt
command -v starship >/dev/null && eval "$(starship init zsh)"
"#;

/// config.fish shipped to the user when they pick fish.
pub(crate) const FISH_CONFIG_TEMPLATE: &str = r#"# ~/.config/fish/config.fish — generated by the Artix installer

if status is-interactive
    # Cleaner greeting
    set -g fish_greeting

    # Handy abbreviations (expand as you type)
    abbr -a ll 'ls -lah'
    abbr -a .. 'cd ..'
    abbr -a ... 'cd ../..'
    abbr -a gs 'git status'
    abbr -a gc 'git commit'
    abbr -a gp 'git push'

    # Color ls/grep
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'

    # Starship prompt
    command -v starship >/dev/null && starship init fish | source
end
"#;

pub(crate) const KITTY_CONFIG_TEMPLATE: &str = r#"# vim:ft=kitty

## name:     Catppuccin Kitty Mocha
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!

# The basic colors
foreground              #cdd6f4
background              #1e1e2e
selection_foreground    #1e1e2e
selection_background    #f5e0dc

# Cursor colors
cursor                  #f5e0dc
cursor_text_color       #1e1e2e

# URL underline color when hovering with mouse
url_color               #f5e0dc

# Kitty window border colors
active_border_color     #b4befe
inactive_border_color   #6c7086
bell_border_color       #f9e2af

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #11111b
active_tab_background   #cba6f7
inactive_tab_foreground #cdd6f4
inactive_tab_background #181825
tab_bar_background      #11111b

# Colors for marks (marked text in the terminal)
mark1_foreground #1e1e2e
mark1_background #b4befe
mark2_foreground #1e1e2e
mark2_background #cba6f7
mark3_foreground #1e1e2e
mark3_background #74c7ec

# The 16 terminal colors

# black
color0 #45475a
color8 #585b70

# red
color1 #f38ba8
color9 #f38ba8

# green
color2  #a6e3a1
color10 #a6e3a1

# yellow
color3  #f9e2af
color11 #f9e2af

# blue
color4  #89b4fa
color12 #89b4fa

# magenta
color5  #f5c2e7
color13 #f5c2e7

# cyan
color6  #94e2d5
color14 #94e2d5

# white
color7  #bac2de
color15 #a6adc8

tab_bar_min_tabs            1
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

background_opacity 0.8

"#;

/// fastfetch config (the user's JSONC) and its logo image, embedded at compile
/// time so they ship inside the installer binary — no ISO asset dependency.
/// Both are written into ~/.config/fastfetch on the installed system.
/// Paths are relative to THIS source file (src/system/ → ../assets/).
/// Reliable rollback helper installed to /usr/local/bin/artix-rollback. It swaps
/// the root subvolume @ for a snapshot AND repoints the btrfs default subvolume,
/// so it works no matter how the system boots — a subvol=@ pin or the default
/// subvolume, under GRUB, rEFInd or Limine. Bilingual via $LANG. This is the
/// dependable path; native `snapper rollback` also works when set up (Path A).
pub(crate) const ROLLBACK_SCRIPT: &str = include_str!("../../assets/sh/rollback-script.sh");

/// mkinitcpio *install* hook (`/etc/initcpio/install/artix-rollback`). Bundles
/// the artix-rollback tool (the installer binary, which doubles as the rollback
/// picker) plus btrfs/mount/umount into the initramfs and pulls in the run-time
/// hook. Only matters when the kernel is booted with `artix.rollback`.
pub(crate) const ROLLBACK_INITCPIO_INSTALL: &str =
    include_str!("../../assets/sh/rollback-initcpio-install.sh");

/// mkinitcpio *run-time* hook (`/etc/initcpio/hooks/artix-rollback`). Runs as a
/// latehook — after `encrypt` has unlocked the root, before the root is mounted.
/// If the kernel was booted with `artix.rollback` it mounts the btrfs pool
/// top-level and launches the picker; the chosen snapshot becomes the new @ and
/// the boot continues into it, read-write (no overlay, any kernel, any
/// bootloader). Without the parameter it does nothing, so normal boots are
/// untouched.
pub(crate) const ROLLBACK_INITCPIO_HOOK: &str =
    include_str!("../../assets/sh/rollback-initcpio-hook.sh");

/// A custom GRUB generator (`/etc/grub.d/45_artix_rollback`, runs after
/// 10_linux) that emits one top-level "System Rollback" menuentry. It mirrors
/// the normal boot through grub-mkconfig_lib — so btrfs-subvolume and cryptodisk
/// access are handled exactly the way 10_linux handles them — and appends
/// `artix.rollback` to the cmdline so the initramfs picker runs at boot.
/// @@VMLINUZ@@/@@INITRD@@ are substituted with the chosen kernel at install.
/// Bilingual (Ukrainian + English) Secure Boot instructions, written to the
/// user's home when Secure Boot preparation is enabled. @@KERNEL@@ is replaced
/// with the actual vmlinuz filename. Deliberately blunt about the two things the
/// installer cannot do for the user (Setup Mode in firmware; enrollment on the
/// live system) and about the brick risk.
pub(crate) const SECUREBOOT_README: &str = r#"================================================================
  SECURE BOOT — ЗАВЕРШЕННЯ НАЛАШТУВАННЯ (українською нижче)
  SECURE BOOT — FINISHING SETUP (English below)
================================================================

The installer PREPARED Secure Boot but did NOT enable it. Enabling it
must be done by YOU, on this running system, because it requires putting
your firmware into "Setup Mode" by hand and cannot be automated safely.

  !!! WARNING: On some firmware, enrolling keys incorrectly can BRICK
  !!! the machine (make it unbootable permanently). Proceed only if you
  !!! understand this risk. Keep a backup and know how to reset your
  !!! firmware's Secure Boot settings before you start.

What the installer already did:
  - installed  sbctl
  - generated your signing keys ( sbctl create-keys )

Remaining steps (run as root, on THIS installed system — not a live ISO):

  1. Reboot, enter your UEFI/BIOS setup, and switch Secure Boot to
     "Setup Mode" (the exact menu differs by vendor — look for
     "Secure Boot" -> "Erase/Clear keys" or "Setup Mode"). Save & boot
     back into Artix.

  2. Enroll your keys. To keep Microsoft's keys too (recommended for most
     laptops, safer against bricking):
         sbctl enroll-keys -m
     Only if you know your firmware doesn't need Microsoft's keys:
         sbctl enroll-keys

  3. Sign your kernel:
         sbctl sign -s /boot/@@KERNEL@@

  4. Check everything is signed:
         sbctl verify

  5. Reboot, enter UEFI/BIOS, ENABLE Secure Boot, save & boot.

  6. Confirm it worked:
         sbctl status
     "Secure Boot: enabled" and "Setup Mode: disabled" means success.

From now on, sbctl's pacman hook re-signs the kernel automatically on
every update — you don't need to repeat step 3.

================================================================
  УКРАЇНСЬКОЮ
================================================================

Інсталятор ПІДГОТУВАВ Secure Boot, але НЕ вмикав його. Увімкнути має
саме ТИ, вже на цій встановленій системі, бо це потребує ручного
переходу прошивки в режим "Setup Mode" і не може бути автоматизовано
безпечно.

  !!! УВАГА: на деяких прошивках неправильне занесення ключів може
  !!! ЗАКИРПИЧИТИ комп'ютер (зробити його назавжди незавантажуваним).
  !!! Продовжуй лише якщо розумієш цей ризик. Май резервну копію і знай,
  !!! як скинути налаштування Secure Boot у своїй прошивці, ПЕРЕД початком.

Що інсталятор уже зробив:
  - встановив  sbctl
  - згенерував твої ключі підпису ( sbctl create-keys )

Що лишилось (виконуй від root, на ЦІЙ встановленій системі — не з live-ISO):

  1. Перезавантажся, зайди в UEFI/BIOS і переведи Secure Boot у режим
     "Setup Mode" (точне меню залежить від виробника — шукай
     "Secure Boot" -> "Erase/Clear keys" або "Setup Mode"). Збережи й
     завантажся назад в Artix.

  2. Занеси свої ключі. Щоб зберегти й ключі Microsoft (рекомендовано для
     більшості ноутбуків, безпечніше від закирпичення):
         sbctl enroll-keys -m
     Лише якщо певен, що твоїй прошивці не потрібні ключі Microsoft:
         sbctl enroll-keys

  3. Підпиши своє ядро:
         sbctl sign -s /boot/@@KERNEL@@

  4. Перевір, що все підписано:
         sbctl verify

  5. Перезавантажся, зайди в UEFI/BIOS, УВІМКНИ Secure Boot, збережи й
     завантажся.

  6. Підтверди, що спрацювало:
         sbctl status
     "Secure Boot: enabled" і "Setup Mode: disabled" означає успіх.

Відтепер pacman-hook від sbctl автоматично переписує підпис ядра при
кожному оновленні — крок 3 повторювати не треба.
"#;

/// Chainloader entries for neighbouring OS loaders on every ESP — the piece
/// os-prober cannot do when a neighbour keeps its kernels on its ESP.
pub(crate) const GRUB_NEIGHBOUR_CHAIN: &str =
    include_str!("../../assets/sh/grub-neighbour-chain.sh");

pub(crate) const ARTIX_ROLLBACK_GRUBD: &str =
    include_str!("../../assets/sh/artix-rollback-grubd.sh");

/// Desktop launcher for the rollback menu: opens `artix-rollback` in the user's
/// default terminal (Terminal=true), where sudo can prompt for the password and
/// the snapshot menu is interactive. Bilingual Name/Comment via locale.
pub(crate) const ROLLBACK_DESKTOP: &str = "\
[Desktop Entry]
Type=Application
Name=System Rollback
Name[uk]=Відкат системи
Comment=Roll the system back to a btrfs snapshot
Comment[uk]=Відкотити систему до знімка btrfs
Exec=sudo artix-rollback
Icon=document-revert
Terminal=true
Categories=System;Utility;
Keywords=snapshot;rollback;btrfs;restore;
";

/// Shared `log`/`warn` for the boot-time services below, installed to
/// /usr/local/lib/artix-installer/log.sh and sourced by path.
///
/// It has to be a real file, not text pasted into each script: the services do
/// their work inside `setsid sh -c '...'`, a fresh shell that inherits no
/// functions, and that block is already single-quoted so a definition cannot be
/// nested into it cleanly. Sourcing by path is the one thing that works there.
///
/// This must be written BEFORE any script that sources it.
pub(crate) const LOG_LIB: &str = include_str!("../../assets/sh/lib-log.sh");

/// Repair ownership and permissions on an installed system — the way back from
/// `chmod 777 /`, a stray `chown -R`, or the slip of typing `chown` where
/// `chmod` was meant (the mode lands as a UID and /home ends up owned by a user
/// that does not exist). Run from the RECOVERY screen inside the target's
/// chroot, not during an install.
///
/// Two passes: a fixed table of paths whose right answer is not written down
/// anywhere on disk (/, /tmp, the shadow files, ssh host keys, each user's own
/// home) — offline and instant, and enough to make the machine usable again —
/// then every packaged file restored from the package database, which is the
/// only authority on the rest, setuid binaries included.
pub(crate) const FIX_PERMISSIONS: &str = include_str!("../../assets/sh/fix-permissions.sh");

/// First-boot baseline snapshot. snapper can't run inside the installer chroot
/// (no D-Bus → "fatal library error"), so this one-shot script runs on the first
/// real boot, where snapper works. It detaches into the background (so boot is
/// never delayed), retries until snapper is ready, takes a "clean system"
/// snapshot, refreshes the GRUB menu, then removes its own boot.d symlink so it
/// only ever runs once. This is also the first entry to populate the GRUB submenu.
pub(crate) const FIRST_SNAPSHOT_SCRIPT: &str =
    include_str!("../../assets/sh/first-snapshot-script.sh");

/// dinit service that fires the baseline-snapshot script at boot. `scripted`
/// means dinit considers it started the moment the command exits — and the
/// command returns immediately (the real work is detached), so the boot target
/// is never held up.
pub(crate) const FIRST_SNAPSHOT_SERVICE: &str = "\
# Managed by the Artix installer: one-time baseline snapshot on first boot.
# The script detaches its work and removes this service's boot.d symlink once
# the snapshot is taken. See /usr/local/lib/artix-installer/first-snapshot.sh.
type = scripted
command = /usr/local/lib/artix-installer/first-snapshot.sh
restart = false
";

/// Session entry for Pinnacle in the form the project wants it shipped:
/// the STOCK filename `pinnacle.desktop`, plain `pinnacle --session`. NOT
/// pre-written to wayland-sessions (the package owns that path — pre-writing it
/// would make pacman abort on a file conflict). Instead this content is stashed
/// under /usr/share/artix-installer/ and copied over the package's file by a
/// PostTransaction pacman hook after every pinnacle-comp install/upgrade. The
/// dbus-run-session fallback lives next to it as pinnacleFree.desktop.
pub(crate) const PINNACLE_SESSION_DESKTOP: &str = "\
[Desktop Entry]\n\
Name=Pinnacle\n\
Comment=A Wayland compositor inspired by AwesomeWM\n\
Exec=pinnacle --session\n\
Type=Application\n\
DesktopNames=pinnacle\n\
";

/// pacman hook that keeps the Pinnacle session entry ours across package
/// updates. `zz-` so it sorts (and runs) after the package's own hooks.
pub(crate) const PINNACLE_SESSION_HOOK: &str = "\
[Trigger]\n\
Operation = Install\n\
Operation = Upgrade\n\
Type = Package\n\
Target = pinnacle-comp*\n\
\n\
[Action]\n\
Description = Keeping the Artix Pinnacle session entry (pinnacle --session)...\n\
When = PostTransaction\n\
Exec = /usr/bin/install -Dm644 /usr/share/artix-installer/pinnacle-session.desktop /usr/share/wayland-sessions/pinnacle.desktop\n\
";

/// Regenerate grub.cfg after a KERNEL change (a new vmlinuz lands/leaves) or a
/// GRUB upgrade. Arch/Artix's grub package does NOT do this itself, so without a
/// hook a new kernel never reaches the menu and — for dual boot — the neighbour
/// generator (35_artix_neighbours) never re-runs, so a system installed later
/// stays invisible until someone runs grub-mkconfig by hand. `zz-` so it fires
/// AFTER the initramfs is rebuilt (grub.cfg then points at a real initramfs).
/// The generator is best-effort (always exits 0), so this can't break an
/// update. Two [Trigger] blocks: kernel image paths, and the grub package.
pub(crate) const GRUB_REGEN_HOOK: &str = "\
[Trigger]\n\
Operation = Install\n\
Operation = Upgrade\n\
Operation = Remove\n\
Type = Path\n\
Target = usr/lib/modules/*/vmlinuz\n\
\n\
[Trigger]\n\
Operation = Upgrade\n\
Type = Package\n\
Target = grub\n\
\n\
[Action]\n\
Description = Regenerating GRUB config (kernels + neighbour-OS menu)...\n\
When = PostTransaction\n\
Exec = /usr/bin/grub-mkconfig -o /boot/grub/grub.cfg\n\
";

/// Refresh the frozen rescue kernel pair AFTER a successful normal boot. Never
/// runs on a rollback/rescue boot (artix.rollback on the cmdline), so a broken
/// live kernel can never overwrite the known-good pair: if the machine fails to
/// boot, this service simply never fires under the broken kernel.
pub(crate) const RESCUE_SYNC_SCRIPT: &str = include_str!("../../assets/sh/rescue-sync-script.sh");

pub(crate) const RESCUE_SYNC_SERVICE: &str = r#"# Managed by the Artix installer: refresh the rescue kernel pair after a
# successful boot. See /usr/local/lib/artix-installer/rescue-sync.sh.
type = scripted
command = /usr/local/lib/artix-installer/rescue-sync.sh
restart = false
"#;

/// One-shot after a snapshot rollback: reconcile /boot with the restored root.
/// When /boot lives outside the btrfs pool (own partition / the ESP), swapping
/// @ does NOT swap the kernel there — the live vmlinuz can be newer than the
/// snapshot's /usr/lib/modules. Triggered by the fixup-pending flag that the
/// rollback tool drops into the freshly restored @.
pub(crate) const ROLLBACK_FIXUP_SCRIPT: &str =
    include_str!("../../assets/sh/rollback-fixup-script.sh");

pub(crate) const ROLLBACK_FIXUP_SERVICE: &str = r#"# Managed by the Artix installer: one-shot /boot reconciliation after a
# snapshot rollback. See /usr/local/lib/artix-installer/rollback-fixup.sh.
type = scripted
command = /usr/local/lib/artix-installer/rollback-fixup.sh
restart = false
"#;

/// Wrapper the shipped pinnacle.toml points at instead of a bare `cargo run`:
/// builds the Rust config only when sources changed (incremental → instant
/// when clean), execs the release binary, and logs failures where the user can
/// actually find them instead of dying into a configless session.
pub(crate) const PINNACLE_RUN_CONFIG: &str = include_str!("../../assets/sh/pinnacle-run-config.sh");

pub(crate) const FASTFETCH_CONFIG: &str = include_str!("../../assets/fastfetch.jsonc");

pub(crate) const FASTFETCH_LOGO_PNG: &[u8] = include_bytes!("../../assets/fastfetch.png");

/// wofi (Wayland launcher) config + stylesheet, embedded at compile time.
/// Written into ~/.config/wofi only when wofi is among the selected packages
/// (it's Wayland-only, so it's offered as an optional pick, not a default).
pub(crate) const WOFI_CONFIG: &str = include_str!("../../assets/wofi.config");

pub(crate) const WOFI_STYLE_CSS: &str = include_str!("../../assets/wofi.style.css");

/// waybar (Wayland status bar) config + stylesheet, embedded at compile time.
/// Written into ~/.config/waybar only when waybar is among the selected
/// packages (Wayland-only, so an optional pick rather than a default).
pub(crate) const WAYBAR_CONFIG: &str = include_str!("../../assets/waybar.config.jsonc");

pub(crate) const WAYBAR_STYLE_CSS: &str = include_str!("../../assets/waybar.style.css");

/// pinnacle (Wayland compositor) config tree, embedded at compile time as a
/// gzip tarball (Cargo.toml/lock, pinnacle.toml, src/main.rs, scripts/). It's
/// extracted into ~/.config/pinnacle only when pinnacle-comp is among the
/// selected AUR packages. Shipped as one archive because it's a multi-file,
/// multi-directory tree — far cleaner than a dozen include_str! constants.
/// The Pinnacle config tree, as plain files under `assets/pinnacle/`.
///
/// This used to be a single `pinnacle.tar.gz` embedded with `include_bytes!`,
/// which meant the config a user is invited to edit was an opaque 15 KB blob:
/// invisible in review, undiffable in git, and unchangeable without
/// regenerating the whole archive. They're ordinary text files — so they're
/// kept as ordinary text files, and the install writes each one out.
///
/// `Cargo.lock` is deliberately NOT shipped: cargo regenerates it, and a lock
/// frozen at tarball-build time would pin stale dependency versions.
pub(crate) const PINNACLE_FILES: &[(&str, &str)] = &[
    (
        "Cargo.toml",
        include_str!("../../assets/pinnacle/Cargo.toml"),
    ),
    (
        "pinnacle.toml",
        include_str!("../../assets/pinnacle/pinnacle.toml"),
    ),
    (
        "src/main.rs",
        include_str!("../../assets/pinnacle/src/main.rs"),
    ),
    // clipboard.sh is the ONLY script left: launcher.sh and mango-tags.sh were
    // MangoWC leftovers (v239) — the latter spoke `mmsg`, an IPC that doesn't
    // exist under Pinnacle. Their table rows died with the files; a row here
    // without a file is a compile error, which is exactly the guard we want.
    (
        "scripts/clipboard.sh",
        include_str!("../../assets/pinnacle/scripts/clipboard.sh"),
    ),
];

// NOT under assets/sh/: the shebang is `nft -f`, so this is an nftables
// ruleset, not a shell script — dash and shellcheck have no business parsing
// it. It lives with the other non-shell configs (waybar, wofi, fastfetch).
pub(crate) const NFTABLES_CONFIG_TEMPLATE: &str = include_str!("../../assets/nftables.conf");

/// Logging help document, written into the user's home in their chosen
/// language. Explains the install log plus how to use the system's logging
/// (syslog-ng text logs) and service manager (dinit): per-program output,
/// following in real time, and the rest.
pub(crate) const LOG_HELP_UK: &str = r##"# Як читати логи системи

Цей дистрибутив використовує **syslog-ng** для системних логів і **dinit** для
керування службами. Нижче — як знаходити й читати логи.

## Лог встановлення

Повний журнал встановлення цієї системи лежить поряд із цим файлом:

    less ~/installer.log

## Системні логи (syslog-ng)

Логи — це звичайні текстові файли в `/var/log/`:

- `/var/log/everything.log` — усе разом (найзручніше для пошуку)
- `/var/log/messages.log`   — загальні системні повідомлення
- `/var/log/auth.log`       — вхід, sudo, автентифікація
- `/var/log/kernel.log`     — повідомлення ядра
- `/var/log/daemon.log`     — служби та демони

### У реальному часі

Стежити за логом наживо (вийти — Ctrl+C):

    sudo tail -f /var/log/everything.log

### Лише конкретна програма

Відфільтрувати рядки певної програми чи служби:

    sudo grep 'NetworkManager' /var/log/everything.log

Те саме, але наживо:

    sudo tail -f /var/log/everything.log | grep --line-buffered 'sshd'

### Інше корисне

    sudo tail -n 100 /var/log/messages.log          # останні 100 рядків
    sudo grep -i 'error' /var/log/everything.log     # усі помилки
    sudo less +G /var/log/everything.log             # відкрити в кінці
    du -sh /var/log/*.log                            # розмір логів

## Служби (dinit)

    sudo dinitctl list                  # стан усіх служб
    sudo dinitctl status <служба>       # стан однієї
    sudo dinitctl restart <служба>      # перезапуск
    sudo dinitctl start|stop <служба>   # запуск/зупинка

### Користувацькі служби (вашого сеансу, без sudo)

    dinitctl list
    dinitctl catlog <служба>            # переглянути буфер логів служби

---
Згенеровано інсталятором Artix.
"##;

pub(crate) const LOG_HELP_EN: &str = r##"# How to read the system logs

This distribution uses **syslog-ng** for system logs and **dinit** to manage
services. Here is how to find and read logs.

## Install log

The full log of this system's installation sits next to this file:

    less ~/installer.log

## System logs (syslog-ng)

Logs are plain text files under `/var/log/`:

- `/var/log/everything.log` — everything together (best for searching)
- `/var/log/messages.log`   — general system messages
- `/var/log/auth.log`       — logins, sudo, authentication
- `/var/log/kernel.log`     — kernel messages
- `/var/log/daemon.log`     — services and daemons

### In real time

Follow a log live (Ctrl+C to quit):

    sudo tail -f /var/log/everything.log

### One program only

Filter the lines of a given program or service:

    sudo grep 'NetworkManager' /var/log/everything.log

The same, live:

    sudo tail -f /var/log/everything.log | grep --line-buffered 'sshd'

### Other handy commands

    sudo tail -n 100 /var/log/messages.log          # last 100 lines
    sudo grep -i 'error' /var/log/everything.log     # all errors
    sudo less +G /var/log/everything.log             # open at the end
    du -sh /var/log/*.log                            # log sizes

## Services (dinit)

    sudo dinitctl list                  # status of all services
    sudo dinitctl status <service>      # status of one
    sudo dinitctl restart <service>     # restart
    sudo dinitctl start|stop <service>  # start/stop

### User services (your session, no sudo)

    dinitctl list
    dinitctl catlog <service>           # view a service's log buffer

---
Generated by the Artix installer.
"##;

/// Virtual-Wi-Fi test harness, embedded so it works on ANY live medium without
/// depending on the ISO overlay. Loads mac80211_hwsim (two simulated radios),
/// runs hostapd on one as an access point, and leaves the other for
/// NetworkManager — which is what the installer's Wi-Fi screen then sees. Used
/// from the mode screen's "Wi-Fi test" entry; a no-op on real hardware where
/// the module isn't present.
pub(crate) const WIFI_TEST_SCRIPT: &str = include_str!("../../assets/sh/wifi-test-script.sh");
