//! Every file the installer writes into the target system, in one place.
//!
//! Shell scripts (rollback, rescue-sync, mirror optimizer), dinit service
//! definitions, dotfile templates (zsh/fish/kitty), desktop-session entries,
//! pacman hooks, the Secure Boot README, and compile-time embedded assets
//! (waybar/wofi/fastfetch configs, the Pinnacle config tarball).
//!
//! Editing rules: scripts are POSIX sh unless the shebang says otherwise —
//! check with `dash -n`; text destined for `format!` escapes braces or uses
//! @@PLACEHOLDER@@; `include_str!`/`include_bytes!` paths are relative to
//! THIS file (`../../assets/...`).

/// .zshrc shipped to the user when they pick zsh. Mirrors a typical oh-my-zsh
/// feature set using the distro's plugin packages, then starts starship.
pub(crate) const ZSHRC_TEMPLATE: &str = r#"# ~/.zshrc — generated by the Artix installer

# History
HISTFILE=~/.zsh_history
HISTSIZE=50000
SAVEHIST=50000
setopt SHARE_HISTORY HIST_IGNORE_ALL_DUPS HIST_IGNORE_SPACE INC_APPEND_HISTORY

# Completion system
autoload -Uz compinit && compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
setopt AUTO_CD
# Treat '#' as a comment on the interactive prompt too, so pasted commands
# with trailing comments don't error out (off by default in zsh).
setopt INTERACTIVE_COMMENTS

# Plugins (installed from the repos)
[ -f /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ] && \
  source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
[ -f /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh ] && \
  source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
# Syntax highlighting must be sourced last.
[ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && \
  source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# History substring search: bind up/down arrows
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Handy aliases
alias ls='ls --color=auto'
alias ll='ls -lah'
alias grep='grep --color=auto'
alias ..='cd ..'

# Starship prompt
command -v starship >/dev/null && eval "$(starship init zsh)"
"#;

/// config.fish shipped to the user when they pick fish.
pub(crate) const FISH_CONFIG_TEMPLATE: &str = r#"# ~/.config/fish/config.fish — generated by the Artix installer

if status is-interactive
    # Cleaner greeting
    set -g fish_greeting

    # Handy abbreviations (expand as you type)
    abbr -a ll 'ls -lah'
    abbr -a .. 'cd ..'
    abbr -a ... 'cd ../..'
    abbr -a gs 'git status'
    abbr -a gc 'git commit'
    abbr -a gp 'git push'

    # Color ls/grep
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'

    # Starship prompt
    command -v starship >/dev/null && starship init fish | source
end
"#;

pub(crate) const KITTY_CONFIG_TEMPLATE: &str = r#"# vim:ft=kitty

## name:     Catppuccin Kitty Mocha
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!

# The basic colors
foreground              #cdd6f4
background              #1e1e2e
selection_foreground    #1e1e2e
selection_background    #f5e0dc

# Cursor colors
cursor                  #f5e0dc
cursor_text_color       #1e1e2e

# URL underline color when hovering with mouse
url_color               #f5e0dc

# Kitty window border colors
active_border_color     #b4befe
inactive_border_color   #6c7086
bell_border_color       #f9e2af

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #11111b
active_tab_background   #cba6f7
inactive_tab_foreground #cdd6f4
inactive_tab_background #181825
tab_bar_background      #11111b

# Colors for marks (marked text in the terminal)
mark1_foreground #1e1e2e
mark1_background #b4befe
mark2_foreground #1e1e2e
mark2_background #cba6f7
mark3_foreground #1e1e2e
mark3_background #74c7ec

# The 16 terminal colors

# black
color0 #45475a
color8 #585b70

# red
color1 #f38ba8
color9 #f38ba8

# green
color2  #a6e3a1
color10 #a6e3a1

# yellow
color3  #f9e2af
color11 #f9e2af

# blue
color4  #89b4fa
color12 #89b4fa

# magenta
color5  #f5c2e7
color13 #f5c2e7

# cyan
color6  #94e2d5
color14 #94e2d5

# white
color7  #bac2de
color15 #a6adc8

tab_bar_min_tabs            1
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

background_opacity 0.8

"#;

/// fastfetch config (the user's JSONC) and its logo image, embedded at compile
/// time so they ship inside the installer binary — no ISO asset dependency.
/// Both are written into ~/.config/fastfetch on the installed system.
/// Paths are relative to THIS source file (src/system/ → ../assets/).
/// Reliable rollback helper installed to /usr/local/bin/artix-rollback. It swaps
/// the root subvolume @ for a snapshot AND repoints the btrfs default subvolume,
/// so it works no matter how the system boots — a subvol=@ pin or the default
/// subvolume, under GRUB, rEFInd or Limine. Bilingual via $LANG. This is the
/// dependable path; native `snapper rollback` also works when set up (Path A).
pub(crate) const ROLLBACK_SCRIPT: &str = r##"#!/bin/sh
# artix-rollback — roll the btrfs root subvolume (@) back to a snapshot.
# Installed by the Artix installer. Usage: sudo artix-rollback [NUMBER]
set -eu

UK=0
case "${LANG:-}" in uk*|*UA*|*ua*) UK=1 ;; esac
msg() { if [ "$UK" = 1 ]; then printf '%s\n' "$2"; else printf '%s\n' "$1"; fi; }

if [ "$(id -u)" -ne 0 ]; then
    msg "Please run as root: sudo artix-rollback" "Запусти від root: sudo artix-rollback"
    exit 1
fi

DEV=$(findmnt -no SOURCE / | sed 's/\[.*//')
if [ -z "$DEV" ]; then
    msg "Could not determine the root device." "Не вдалося визначити кореневий пристрій."
    exit 1
fi

msg "Available snapshots (config: root):" "Доступні знімки (конфіг: root):"
snapper -c root list || true
echo

N="${1:-}"
if [ -z "$N" ]; then
    if [ "$UK" = 1 ]; then printf 'Номер знімка для відкату: '; else printf 'Snapshot number to roll back to: '; fi
    read -r N
fi
case "$N" in ''|*[!0-9]*)
    msg "Invalid snapshot number." "Хибний номер знімка."
    exit 1 ;;
esac

TOP=$(mktemp -d)
cleanup() { umount "$TOP" 2>/dev/null || true; rmdir "$TOP" 2>/dev/null || true; }
trap cleanup EXIT INT TERM
mount -o subvolid=5 "$DEV" "$TOP"

if [ ! -d "$TOP/@snapshots/$N/snapshot" ]; then
    msg "Snapshot $N not found." "Знімок $N не знайдено."
    exit 1
fi

STAMP=$(date +%Y%m%d-%H%M%S)
msg "Backing up the current root to @.rollback-$STAMP ..." "Резервую поточний корінь у @.rollback-$STAMP ..."
mv "$TOP/@" "$TOP/@.rollback-$STAMP"
msg "Creating a new root from snapshot $N ..." "Створюю новий корінь зі знімка $N ..."
btrfs subvolume snapshot "$TOP/@snapshots/$N/snapshot" "$TOP/@" >/dev/null

# snap-pac takes its PRE snapshot while pacman still holds /var/lib/pacman/db.lck,
# so a snapshot can carry that stale lock. Drop it in the new root, otherwise the
# rolled-back system reports "unable to lock database". Also clear the resolved
# pacman sync caches' lock if present.
rm -f "$TOP/@/var/lib/pacman/db.lck" 2>/dev/null

# Repoint the btrfs default at the new @ so a default-subvolume boot follows the
# rollback too (a subvol=@ pin already mounts @ by name).
NEWID=$(btrfs subvolume show "$TOP/@" | sed -n 's/.*Subvolume ID:[[:space:]]*//p')
if [ -n "$NEWID" ]; then btrfs subvolume set-default "$NEWID" "$TOP"; fi

# Ask the restored root's first boot to reconcile /boot with the snapshot
# (kernel image, initramfs, boot menu, rescue pair) - consumed by the
# artix-rollback-fixup one-shot service.
mkdir -p "$TOP/@/var/lib/artix-rollback"
: > "$TOP/@/var/lib/artix-rollback/fixup-pending"

echo
msg "Done. Reboot to boot snapshot $N." "Готово. Перезавантаж, щоб працювати на знімку $N."
msg "The old root is kept as @.rollback-$STAMP (delete later with btrfs subvolume delete)." "Старий корінь збережено як @.rollback-$STAMP (видали згодом через btrfs subvolume delete)."
echo
if [ "$UK" = 1 ]; then printf 'Перезавантажити зараз? [y/N] '; else printf 'Reboot now? [y/N] '; fi
read -r ans
case "$ans" in y|Y) reboot ;; esac
"##;

/// mkinitcpio *install* hook (`/etc/initcpio/install/artix-rollback`). Bundles
/// the artix-rollback tool (the installer binary, which doubles as the rollback
/// picker) plus btrfs/mount/umount into the initramfs and pulls in the run-time
/// hook. Only matters when the kernel is booted with `artix.rollback`.
pub(crate) const ROLLBACK_INITCPIO_INSTALL: &str = r#"#!/bin/bash
# Managed by the Artix installer.
build() {
    add_binary /usr/local/bin/artix-rollback
    add_binary btrfs
    add_binary mount
    add_binary umount
    add_binary /usr/bin/sync
    add_runscript
}
help() {
    echo "Artix snapshot rollback picker for early boot (kernel param: artix.rollback)."
}
"#;

/// mkinitcpio *run-time* hook (`/etc/initcpio/hooks/artix-rollback`). Runs as a
/// latehook — after `encrypt` has unlocked the root, before the root is mounted.
/// If the kernel was booted with `artix.rollback` it mounts the btrfs pool
/// top-level and launches the picker; the chosen snapshot becomes the new @ and
/// the boot continues into it, read-write (no overlay, any kernel, any
/// bootloader). Without the parameter it does nothing, so normal boots are
/// untouched.
pub(crate) const ROLLBACK_INITCPIO_HOOK: &str = r#"#!/bin/bash
# Managed by the Artix installer.
run_latehook() {
    if grep -qw artix.rollback /proc/cmdline 2>/dev/null; then
        local dev
        dev="$(resolve_device "${root}" 2>/dev/null)" || dev="${root}"
        [ -n "$dev" ] || return 0
        mkdir -p /run/artix-rb
        if mount -o subvolid=5 "$dev" /run/artix-rb 2>/dev/null; then
            /usr/local/bin/artix-rollback --rollback-initramfs /run/artix-rb <>/dev/console 1>&0 2>&0
            # Second commit layer (the picker already commits, but it may exit
            # early or crash mid-swap): flush page cache and force a btrfs
            # transaction commit so the swapped @ is fully on disk BEFORE we
            # release the pool. Then release cleanly — falling back to a lazy
            # umount so a transient EBUSY can't leave the pool mounted and block
            # the init's root mount. This is what guarantees the very next mount
            # of the SAME device (the real root, subvol=@) sees the new @ on the
            # first try, on every bootloader.
            sync 2>/dev/null
            btrfs filesystem sync /run/artix-rb 2>/dev/null
            umount /run/artix-rb 2>/dev/null || umount -l /run/artix-rb 2>/dev/null
        fi
    fi
}
"#;

/// A custom GRUB generator (`/etc/grub.d/45_artix_rollback`, runs after
/// 10_linux) that emits one top-level "System Rollback" menuentry. It mirrors
/// the normal boot through grub-mkconfig_lib — so btrfs-subvolume and cryptodisk
/// access are handled exactly the way 10_linux handles them — and appends
/// `artix.rollback` to the cmdline so the initramfs picker runs at boot.
/// @@VMLINUZ@@/@@INITRD@@ are substituted with the chosen kernel at install.
/// Bilingual (Ukrainian + English) Secure Boot instructions, written to the
/// user's home when Secure Boot preparation is enabled. @@KERNEL@@ is replaced
/// with the actual vmlinuz filename. Deliberately blunt about the two things the
/// installer cannot do for the user (Setup Mode in firmware; enrollment on the
/// live system) and about the brick risk.
pub(crate) const SECUREBOOT_README: &str = r#"================================================================
  SECURE BOOT — ЗАВЕРШЕННЯ НАЛАШТУВАННЯ (українською нижче)
  SECURE BOOT — FINISHING SETUP (English below)
================================================================

The installer PREPARED Secure Boot but did NOT enable it. Enabling it
must be done by YOU, on this running system, because it requires putting
your firmware into "Setup Mode" by hand and cannot be automated safely.

  !!! WARNING: On some firmware, enrolling keys incorrectly can BRICK
  !!! the machine (make it unbootable permanently). Proceed only if you
  !!! understand this risk. Keep a backup and know how to reset your
  !!! firmware's Secure Boot settings before you start.

What the installer already did:
  - installed  sbctl
  - generated your signing keys ( sbctl create-keys )

Remaining steps (run as root, on THIS installed system — not a live ISO):

  1. Reboot, enter your UEFI/BIOS setup, and switch Secure Boot to
     "Setup Mode" (the exact menu differs by vendor — look for
     "Secure Boot" -> "Erase/Clear keys" or "Setup Mode"). Save & boot
     back into Artix.

  2. Enroll your keys. To keep Microsoft's keys too (recommended for most
     laptops, safer against bricking):
         sbctl enroll-keys -m
     Only if you know your firmware doesn't need Microsoft's keys:
         sbctl enroll-keys

  3. Sign your kernel:
         sbctl sign -s /boot/@@KERNEL@@

  4. Check everything is signed:
         sbctl verify

  5. Reboot, enter UEFI/BIOS, ENABLE Secure Boot, save & boot.

  6. Confirm it worked:
         sbctl status
     "Secure Boot: enabled" and "Setup Mode: disabled" means success.

From now on, sbctl's pacman hook re-signs the kernel automatically on
every update — you don't need to repeat step 3.

================================================================
  УКРАЇНСЬКОЮ
================================================================

Інсталятор ПІДГОТУВАВ Secure Boot, але НЕ вмикав його. Увімкнути має
саме ТИ, вже на цій встановленій системі, бо це потребує ручного
переходу прошивки в режим "Setup Mode" і не може бути автоматизовано
безпечно.

  !!! УВАГА: на деяких прошивках неправильне занесення ключів може
  !!! ЗАКИРПИЧИТИ комп'ютер (зробити його назавжди незавантажуваним).
  !!! Продовжуй лише якщо розумієш цей ризик. Май резервну копію і знай,
  !!! як скинути налаштування Secure Boot у своїй прошивці, ПЕРЕД початком.

Що інсталятор уже зробив:
  - встановив  sbctl
  - згенерував твої ключі підпису ( sbctl create-keys )

Що лишилось (виконуй від root, на ЦІЙ встановленій системі — не з live-ISO):

  1. Перезавантажся, зайди в UEFI/BIOS і переведи Secure Boot у режим
     "Setup Mode" (точне меню залежить від виробника — шукай
     "Secure Boot" -> "Erase/Clear keys" або "Setup Mode"). Збережи й
     завантажся назад в Artix.

  2. Занеси свої ключі. Щоб зберегти й ключі Microsoft (рекомендовано для
     більшості ноутбуків, безпечніше від закирпичення):
         sbctl enroll-keys -m
     Лише якщо певен, що твоїй прошивці не потрібні ключі Microsoft:
         sbctl enroll-keys

  3. Підпиши своє ядро:
         sbctl sign -s /boot/@@KERNEL@@

  4. Перевір, що все підписано:
         sbctl verify

  5. Перезавантажся, зайди в UEFI/BIOS, УВІМКНИ Secure Boot, збережи й
     завантажся.

  6. Підтверди, що спрацювало:
         sbctl status
     "Secure Boot: enabled" і "Setup Mode: disabled" означає успіх.

Відтепер pacman-hook від sbctl автоматично переписує підпис ядра при
кожному оновленні — крок 3 повторювати не треба.
"#;

pub(crate) const ARTIX_ROLLBACK_GRUBD: &str = r#"#!/bin/sh
# Managed by the Artix installer. Adds a "System Rollback" GRUB entry that boots
# the FROZEN RESCUE kernel/initramfs (falling back to the live pair) with
# artix.rollback so the early-boot snapshot picker runs — even when a kernel
# update broke the live kernel. Device access mirrors 10_linux via
# grub-mkconfig_lib.
set -e
. /usr/share/grub/grub-mkconfig_lib
RESCUE=1
K="/boot/vmlinuz-artix-rescue"
I="/boot/initramfs-artix-rescue.img"
if [ ! -e "$K" ] || [ ! -e "$I" ]; then
    RESCUE=0
    K="/boot/@@VMLINUZ@@"
    I="/boot/@@INITRD@@"
fi
[ -e "$K" ] || exit 0
. /etc/default/grub 2>/dev/null || true
dev="$("${grub_probe:-grub-probe}" --target=device "$K")"
rk="$(make_system_path_relative_to_its_root "$K")"
ri="$(make_system_path_relative_to_its_root "$I")"
uc=""
for u in intel-ucode.img amd-ucode.img; do
    [ -f "/boot/$u" ] && uc="$uc $(make_system_path_relative_to_its_root "/boot/$u")"
done
printf "%s\n" "menuentry 'Artix - System Rollback (pick a snapshot)' --class artix --class gnu-linux {"
prepare_grub_to_access_device "$dev"
printf "\tlinux %s rootflags=subvol=@ %s %s artix.rollback\n" "$rk" "$GRUB_CMDLINE_LINUX" "$GRUB_CMDLINE_LINUX_DEFAULT"
printf "\tinitrd%s %s\n" "$uc" "$ri"
printf "}\n"
# Plain boot on the frozen rescue pair - the escape hatch when a kernel update
# broke the live kernel and /boot lives OUTSIDE the btrfs pool (encrypted
# /boot partition), where a snapshot rollback alone cannot restore /boot.
if [ "$RESCUE" = 1 ]; then
printf "%s\n" "menuentry 'Artix - rescue kernel (known good)' --class artix --class gnu-linux {"
prepare_grub_to_access_device "$dev"
printf "\tlinux %s rootflags=subvol=@ %s %s\n" "$rk" "$GRUB_CMDLINE_LINUX" "$GRUB_CMDLINE_LINUX_DEFAULT"
printf "\tinitrd%s %s\n" "$uc" "$ri"
printf "}\n"
fi
"#;

/// Desktop launcher for the rollback menu: opens `artix-rollback` in the user's
/// default terminal (Terminal=true), where sudo can prompt for the password and
/// the snapshot menu is interactive. Bilingual Name/Comment via locale.
pub(crate) const ROLLBACK_DESKTOP: &str = "\
[Desktop Entry]
Type=Application
Name=System Rollback
Name[uk]=Відкат системи
Comment=Roll the system back to a btrfs snapshot
Comment[uk]=Відкотити систему до знімка btrfs
Exec=sudo artix-rollback
Icon=document-revert
Terminal=true
Categories=System;Utility;
Keywords=snapshot;rollback;btrfs;restore;
";

/// First-boot baseline snapshot. snapper can't run inside the installer chroot
/// (no D-Bus → "fatal library error"), so this one-shot script runs on the first
/// real boot, where snapper works. It detaches into the background (so boot is
/// never delayed), retries until snapper is ready, takes a "clean system"
/// snapshot, refreshes the GRUB menu, then removes its own boot.d symlink so it
/// only ever runs once. This is also the first entry to populate the GRUB submenu.
pub(crate) const FIRST_SNAPSHOT_SCRIPT: &str = r##"#!/bin/sh
# One-time baseline snapshot of the freshly installed system (first boot only).
MARKER=/var/lib/artix-installer/baseline-snapshot-done
[ -f "$MARKER" ] && exit 0

# Detach so boot is never blocked; retry until snapper/D-Bus are up.
setsid sh -c '
    i=0
    while [ "$i" -lt 60 ]; do
        if snapper -c root create -d "clean system (post-install baseline)" >/dev/null 2>&1; then
            mkdir -p /var/lib/artix-installer
            : > /var/lib/artix-installer/baseline-snapshot-done
            if [ -d /boot/grub ] && command -v grub-mkconfig >/dev/null 2>&1; then
                grub-mkconfig -o /boot/grub/grub.cfg >/dev/null 2>&1
            fi
            rm -f /etc/dinit.d/boot.d/artix-first-snapshot 2>/dev/null
            break
        fi
        i=$((i + 1))
        sleep 2
    done
' >/dev/null 2>&1 &
exit 0
"##;

/// dinit service that fires the baseline-snapshot script at boot. `scripted`
/// means dinit considers it started the moment the command exits — and the
/// command returns immediately (the real work is detached), so the boot target
/// is never held up.
pub(crate) const FIRST_SNAPSHOT_SERVICE: &str = "\
# Managed by the Artix installer: one-time baseline snapshot on first boot.
# The script detaches its work and removes this service's boot.d symlink once
# the snapshot is taken. See /usr/local/lib/artix-installer/first-snapshot.sh.
type = scripted
command = /usr/local/lib/artix-installer/first-snapshot.sh
restart = false
";

/// Session entry for Pinnacle in the form the project wants it shipped:
/// the STOCK filename `pinnacle.desktop`, plain `pinnacle --session`. NOT
/// pre-written to wayland-sessions (the package owns that path — pre-writing it
/// would make pacman abort on a file conflict). Instead this content is stashed
/// under /usr/share/artix-installer/ and copied over the package's file by a
/// PostTransaction pacman hook after every pinnacle-comp install/upgrade. The
/// dbus-run-session fallback lives next to it as pinnacleFree.desktop.
pub(crate) const PINNACLE_SESSION_DESKTOP: &str = "\
[Desktop Entry]\n\
Name=Pinnacle\n\
Comment=A Wayland compositor inspired by AwesomeWM\n\
Exec=pinnacle --session\n\
Type=Application\n\
DesktopNames=pinnacle\n\
";

/// pacman hook that keeps the Pinnacle session entry ours across package
/// updates. `zz-` so it sorts (and runs) after the package's own hooks.
pub(crate) const PINNACLE_SESSION_HOOK: &str = "\
[Trigger]\n\
Operation = Install\n\
Operation = Upgrade\n\
Type = Package\n\
Target = pinnacle-comp*\n\
\n\
[Action]\n\
Description = Keeping the Artix Pinnacle session entry (pinnacle --session)...\n\
When = PostTransaction\n\
Exec = /usr/bin/install -Dm644 /usr/share/artix-installer/pinnacle-session.desktop /usr/share/wayland-sessions/pinnacle.desktop\n\
";

/// Refresh the frozen rescue kernel pair AFTER a successful normal boot. Never
/// runs on a rollback/rescue boot (artix.rollback on the cmdline), so a broken
/// live kernel can never overwrite the known-good pair: if the machine fails to
/// boot, this service simply never fires under the broken kernel.
pub(crate) const RESCUE_SYNC_SCRIPT: &str = r##"#!/bin/sh
# Managed by the Artix installer: keep /boot/vmlinuz-artix-rescue (+ its
# initramfs) in sync with the newest kernel that has PROVEN it can boot.
grep -qw artix.rollback /proc/cmdline 2>/dev/null && exit 0
# A pending post-rollback fixup owns the pair right now - let it finish (it
# refreshes the pair itself once /boot is reconciled).
[ -f /var/lib/artix-rollback/fixup-pending ] && exit 0
setsid sh -c '
    # 30 s of uptime as the "this kernel boots fine" proxy, then sync once.
    sleep 30
    live=""
    for k in /boot/vmlinuz-*; do
        [ -e "$k" ] || exit 0
        case "$k" in *artix-rescue*) continue ;; esac
        live="$k"; break
    done
    [ -n "$live" ] || exit 0
    init="/boot/initramfs-${live#/boot/vmlinuz-}.img"
    [ -f "$init" ] || exit 0
    # Only sync when the RUNNING kernel IS the live one. Booting the rescue
    # (or any other) kernel proves nothing about the live pair - syncing then
    # could poison the known-good copy with a broken kernel. pacman ships the
    # image at /usr/lib/modules/<ver>/vmlinuz, so identity is a byte compare.
    run="/usr/lib/modules/$(uname -r)/vmlinuz"
    [ -f "$run" ] || exit 0
    l=$(md5sum < "$live" 2>/dev/null | cut -d" " -f1)
    r=$(md5sum < "$run" 2>/dev/null | cut -d" " -f1)
    [ "$l" = "$r" ] || exit 0
    a=$(md5sum < "$live" 2>/dev/null | cut -d" " -f1)
    b=$(md5sum < /boot/vmlinuz-artix-rescue 2>/dev/null | cut -d" " -f1)
    if [ "$a" != "$b" ]; then
        cp -f "$live" /boot/vmlinuz-artix-rescue
        cp -f "$init" /boot/initramfs-artix-rescue.img
        sync
    fi
' >/dev/null 2>&1 &
exit 0
"##;

pub(crate) const RESCUE_SYNC_SERVICE: &str = r#"# Managed by the Artix installer: refresh the rescue kernel pair after a
# successful boot. See /usr/local/lib/artix-installer/rescue-sync.sh.
type = scripted
command = /usr/local/lib/artix-installer/rescue-sync.sh
restart = false
"#;

/// One-shot after a snapshot rollback: reconcile /boot with the restored root.
/// When /boot lives outside the btrfs pool (own partition / the ESP), swapping
/// @ does NOT swap the kernel there — the live vmlinuz can be newer than the
/// snapshot's /usr/lib/modules. Triggered by the fixup-pending flag that the
/// rollback tool drops into the freshly restored @.
pub(crate) const ROLLBACK_FIXUP_SCRIPT: &str = r##"#!/bin/sh
# Managed by the Artix installer: post-rollback /boot reconciliation.
FLAG=/var/lib/artix-rollback/fixup-pending
[ -f "$FLAG" ] || exit 0
setsid sh -c '
    # Reinstall the kernel image(s) that belong to the RESTORED root: every
    # /usr/lib/modules/<ver> ships its vmlinuz + pkgbase (linux, linux-lts, …).
    for d in /usr/lib/modules/*/; do
        [ -f "${d}vmlinuz" ] && [ -f "${d}pkgbase" ] || continue
        install -Dm644 "${d}vmlinuz" "/boot/vmlinuz-$(cat "${d}pkgbase")"
    done
    mkinitcpio -P >/dev/null 2>&1
    if [ -d /boot/grub ] && command -v grub-mkconfig >/dev/null 2>&1; then
        grub-mkconfig -o /boot/grub/grub.cfg >/dev/null 2>&1
    fi
    # This very boot proved the restored kernel works — refresh the rescue pair.
    live=""
    for k in /boot/vmlinuz-*; do
        case "$k" in *artix-rescue*) continue ;; esac
        [ -e "$k" ] && { live="$k"; break; }
    done
    if [ -n "$live" ]; then
        init="/boot/initramfs-${live#/boot/vmlinuz-}.img"
        [ -f "$init" ] && cp -f "$live" /boot/vmlinuz-artix-rescue                        && cp -f "$init" /boot/initramfs-artix-rescue.img
    fi
    sync
    rm -f /var/lib/artix-rollback/fixup-pending
' >/dev/null 2>&1 &
exit 0
"##;

pub(crate) const ROLLBACK_FIXUP_SERVICE: &str = r#"# Managed by the Artix installer: one-shot /boot reconciliation after a
# snapshot rollback. See /usr/local/lib/artix-installer/rollback-fixup.sh.
type = scripted
command = /usr/local/lib/artix-installer/rollback-fixup.sh
restart = false
"#;

/// Wrapper the shipped pinnacle.toml points at instead of a bare `cargo run`:
/// builds the Rust config only when sources changed (incremental → instant
/// when clean), execs the release binary, and logs failures where the user can
/// actually find them instead of dying into a configless session.
pub(crate) const PINNACLE_RUN_CONFIG: &str = r##"#!/bin/sh
# Managed by the Artix installer. pinnacle.toml runs THIS instead of a bare
# `cargo run`: same effect, but the release profile is used and failures are
# logged. `cargo build` is incremental - after the installer's prebuild it
# returns in milliseconds, and it transparently rebuilds after you edit
# src/main.rs (then just reload the config from inside Pinnacle).
cd "$(dirname "$0")" || exit 1
if ! cargo build --release --locked >run-config.log 2>&1; then
    command -v notify-send >/dev/null 2>&1 && \
        notify-send "Pinnacle config" "Build failed - see ~/.config/pinnacle/run-config.log"
    exit 1
fi
exec ./target/release/pinnacle-config
"##;

pub(crate) const FASTFETCH_CONFIG: &str = include_str!("../../assets/fastfetch.jsonc");

pub(crate) const FASTFETCH_LOGO_PNG: &[u8] = include_bytes!("../../assets/fastfetch.png");

/// wofi (Wayland launcher) config + stylesheet, embedded at compile time.
/// Written into ~/.config/wofi only when wofi is among the selected packages
/// (it's Wayland-only, so it's offered as an optional pick, not a default).
pub(crate) const WOFI_CONFIG: &str = include_str!("../../assets/wofi.config");

pub(crate) const WOFI_STYLE_CSS: &str = include_str!("../../assets/wofi.style.css");

/// waybar (Wayland status bar) config + stylesheet, embedded at compile time.
/// Written into ~/.config/waybar only when waybar is among the selected
/// packages (Wayland-only, so an optional pick rather than a default).
pub(crate) const WAYBAR_CONFIG: &str = include_str!("../../assets/waybar.config.jsonc");

pub(crate) const WAYBAR_STYLE_CSS: &str = include_str!("../../assets/waybar.style.css");

/// pinnacle (Wayland compositor) config tree, embedded at compile time as a
/// gzip tarball (Cargo.toml/lock, pinnacle.toml, src/main.rs, scripts/). It's
/// extracted into ~/.config/pinnacle only when pinnacle-comp is among the
/// selected AUR packages. Shipped as one archive because it's a multi-file,
/// multi-directory tree — far cleaner than a dozen include_str! constants.
pub(crate) const PINNACLE_CONFIG_TARBALL: &[u8] = include_bytes!("../../assets/pinnacle.tar.gz");

pub(crate) const NFTABLES_CONFIG_TEMPLATE: &str = r#"#!/usr/sbin/nft -f
#
# Default-deny stateful firewall for an Artix/dinit desktop.
# Inbound is dropped except for established/related, loopback, ICMP, mDNS, and
# the explicit application ports below. Outbound is allowed.
#
# Installed to /etc/nftables.conf and started via nftables-dinit.

flush ruleset

table inet filter {

    # ── Application port sets ────────────────────────────────────────────────
    # KDE Connect: TCP+UDP 1714-1764 (device pairing, sharing, clipboard, etc.)
    set kdeconnect_ports {
        type inet_service
        flags interval
        elements = { 1714-1764 }
    }

    # LocalSend: TCP+UDP 53317 (HTTP file transfer + multicast discovery).
    set localsend_ports {
        type inet_service
        elements = { 53317 }
    }

    # Sunshine (game streaming, Moonlight host):
    #   TCP 47984, 47989, 47990, 48010
    #   UDP 47998, 47999, 48000, 48002, 48010
    set sunshine_tcp {
        type inet_service
        elements = { 47984, 47989, 47990, 48010 }
    }
    set sunshine_udp {
        type inet_service
        elements = { 47998, 47999, 48000, 48002, 48010 }
    }

    # RustDesk (direct / peer-to-peer connections):
    #   TCP 21115-21119, UDP 21116
    set rustdesk_tcp {
        type inet_service
        flags interval
        elements = { 21115-21119 }
    }
    set rustdesk_udp {
        type inet_service
        elements = { 21116 }
    }

    # Steam Remote Play / In-Home Streaming:
    #   TCP 27036-27037, UDP 27031-27036
    set steam_tcp {
        type inet_service
        flags interval
        elements = { 27036-27037 }
    }
    set steam_udp {
        type inet_service
        flags interval
        elements = { 27031-27036 }
    }

    # Syncthing (file synchronisation):
    #   TCP 22000 (sync), UDP 22000 (QUIC sync), UDP 21027 (local discovery)
    set syncthing_tcp {
        type inet_service
        elements = { 22000 }
    }
    set syncthing_udp {
        type inet_service
        elements = { 22000, 21027 }
    }

    chain input {
        type filter hook input priority filter; policy drop;

        # Stateful: allow what we initiated.
        ct state established,related accept
        ct state invalid drop

        # Loopback.
        iif "lo" accept

        # ICMP / ICMPv6 (ping, path MTU, neighbor discovery).
        ip protocol icmp accept
        ip6 nexthdr ipv6-icmp accept

        # mDNS / Avahi discovery (LocalSend, KDE Connect, printers).
        udp dport 5353 accept

        # SSH (remote administration).
        tcp dport 22 accept

        # ── Applications ──
        tcp dport @kdeconnect_ports accept
        udp dport @kdeconnect_ports accept

        tcp dport @localsend_ports accept
        udp dport @localsend_ports accept

        tcp dport @sunshine_tcp accept
        udp dport @sunshine_udp accept

        tcp dport @rustdesk_tcp accept
        udp dport @rustdesk_udp accept

        tcp dport @steam_tcp accept
        udp dport @steam_udp accept

        tcp dport @syncthing_tcp accept
        udp dport @syncthing_udp accept

        # Everything else: drop (policy).
    }

    chain forward {
        type filter hook forward priority filter; policy drop;
    }

    chain output {
        type filter hook output priority filter; policy accept;
    }
}
"#;

/// Logging help document, written into the user's home in their chosen
/// language. Explains the install log plus how to use the system's logging
/// (syslog-ng text logs) and service manager (dinit): per-program output,
/// following in real time, and the rest.
pub(crate) const LOG_HELP_UK: &str = r##"# Як читати логи системи

Цей дистрибутив використовує **syslog-ng** для системних логів і **dinit** для
керування службами. Нижче — як знаходити й читати логи.

## Лог встановлення

Повний журнал встановлення цієї системи лежить поряд із цим файлом:

    less ~/installer.log

## Системні логи (syslog-ng)

Логи — це звичайні текстові файли в `/var/log/`:

- `/var/log/everything.log` — усе разом (найзручніше для пошуку)
- `/var/log/messages.log`   — загальні системні повідомлення
- `/var/log/auth.log`       — вхід, sudo, автентифікація
- `/var/log/kernel.log`     — повідомлення ядра
- `/var/log/daemon.log`     — служби та демони

### У реальному часі

Стежити за логом наживо (вийти — Ctrl+C):

    sudo tail -f /var/log/everything.log

### Лише конкретна програма

Відфільтрувати рядки певної програми чи служби:

    sudo grep 'NetworkManager' /var/log/everything.log

Те саме, але наживо:

    sudo tail -f /var/log/everything.log | grep --line-buffered 'sshd'

### Інше корисне

    sudo tail -n 100 /var/log/messages.log          # останні 100 рядків
    sudo grep -i 'error' /var/log/everything.log     # усі помилки
    sudo less +G /var/log/everything.log             # відкрити в кінці
    du -sh /var/log/*.log                            # розмір логів

## Служби (dinit)

    sudo dinitctl list                  # стан усіх служб
    sudo dinitctl status <служба>       # стан однієї
    sudo dinitctl restart <служба>      # перезапуск
    sudo dinitctl start|stop <служба>   # запуск/зупинка

### Користувацькі служби (вашого сеансу, без sudo)

    dinitctl list
    dinitctl catlog <служба>            # переглянути буфер логів служби

---
Згенеровано інсталятором Artix.
"##;

pub(crate) const LOG_HELP_EN: &str = r##"# How to read the system logs

This distribution uses **syslog-ng** for system logs and **dinit** to manage
services. Here is how to find and read logs.

## Install log

The full log of this system's installation sits next to this file:

    less ~/installer.log

## System logs (syslog-ng)

Logs are plain text files under `/var/log/`:

- `/var/log/everything.log` — everything together (best for searching)
- `/var/log/messages.log`   — general system messages
- `/var/log/auth.log`       — logins, sudo, authentication
- `/var/log/kernel.log`     — kernel messages
- `/var/log/daemon.log`     — services and daemons

### In real time

Follow a log live (Ctrl+C to quit):

    sudo tail -f /var/log/everything.log

### One program only

Filter the lines of a given program or service:

    sudo grep 'NetworkManager' /var/log/everything.log

The same, live:

    sudo tail -f /var/log/everything.log | grep --line-buffered 'sshd'

### Other handy commands

    sudo tail -n 100 /var/log/messages.log          # last 100 lines
    sudo grep -i 'error' /var/log/everything.log     # all errors
    sudo less +G /var/log/everything.log             # open at the end
    du -sh /var/log/*.log                            # log sizes

## Services (dinit)

    sudo dinitctl list                  # status of all services
    sudo dinitctl status <service>      # status of one
    sudo dinitctl restart <service>     # restart
    sudo dinitctl start|stop <service>  # start/stop

### User services (your session, no sudo)

    dinitctl list
    dinitctl catlog <service>           # view a service's log buffer

---
Generated by the Artix installer.
"##;

/// Virtual-Wi-Fi test harness, embedded so it works on ANY live medium without
/// depending on the ISO overlay. Loads mac80211_hwsim (two simulated radios),
/// runs hostapd on one as an access point, and leaves the other for
/// NetworkManager — which is what the installer's Wi-Fi screen then sees. Used
/// from the mode screen's "Wi-Fi test" entry; a no-op on real hardware where
/// the module isn't present.
pub(crate) const WIFI_TEST_SCRIPT: &str = r###"#!/bin/sh
# ─────────────────────────────────────────────────────────────────────────────
# wifi-test.sh — set up a FAKE Wi-Fi network inside a VM, so the installer's
# Wi-Fi screen can be tested without any real wireless hardware.
#
# Usage (inside the live ISO, as root):
#     sh wifi-test.sh
#
# What it does:
#   1. loads mac80211_hwsim → two simulated radios appear (wlan0, wlan1)
#   2. hands wlan0 to hostapd as an access point broadcasting SSID "ArtixTest"
#   3. leaves wlan1 for NetworkManager → that's what the installer will see
#
# Then, in the installer: pick "configure Wi-Fi" → adapter wlan1 → network
# ArtixTest → password: testtest123
# ─────────────────────────────────────────────────────────────────────────────
set -e

SSID="ArtixTest"
PASS="testtest123"

say() { printf '\n\033[1;36m==>\033[0m %s\n' "$1"; }
die() { printf '\n\033[1;31m!! %s\033[0m\n' "$1"; exit 1; }

# Needs root (modprobe, hostapd, nmcli device set). If launched as a normal
# user, re-exec through sudo rather than just failing — the copy in the live
# user's home is meant to be double-clickable-simple.
if [ "$(id -u)" -ne 0 ]; then
    if command -v sudo >/dev/null 2>&1; then
        say "Needs root — re-running through sudo…"
        exec sudo sh "$0" "$@"
    fi
    die "Run as root:  sudo sh $0"
fi

# ── 1. simulated radios ──────────────────────────────────────────────────────
say "Loading mac80211_hwsim (2 virtual radios)…"
modprobe mac80211_hwsim radios=2 2>/dev/null || die "mac80211_hwsim not available in this kernel"
sleep 1

# The kernel names them wlan0/wlan1 by default, but don't assume — ask.
radios=$(iw dev 2>/dev/null | awk '/Interface/ {print $2}')
ap=$(printf '%s\n' "$radios" | sed -n 1p)
sta=$(printf '%s\n' "$radios" | sed -n 2p)
[ -n "$ap" ] && [ -n "$sta" ] || die "Expected 2 radios, got: $radios"
printf '    AP radio:      %s\n    Client radio:  %s\n' "$ap" "$sta"

# ── 2. keep NetworkManager off the AP radio ──────────────────────────────────
# hostapd owns it; if NM also grabs it, they fight and the AP never comes up.
say "Telling NetworkManager to ignore $ap (hostapd owns it)…"
nmcli device set "$ap" managed no 2>/dev/null || true
rfkill unblock wifi 2>/dev/null || true

# ── 3. bring up the access point ─────────────────────────────────────────────
command -v hostapd >/dev/null 2>&1 || die "hostapd is not installed on this ISO — add it to iso-profile/Packages-Live"

say "Starting access point \"$SSID\" on $ap…"
cat > /tmp/hostapd.conf <<EOF
interface=$ap
driver=nl80211
ssid=$SSID
hw_mode=g
channel=6
wpa=2
wpa_passphrase=$PASS
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
EOF

pkill hostapd 2>/dev/null || true
hostapd -B /tmp/hostapd.conf >/tmp/hostapd.log 2>&1 || die "hostapd failed — see /tmp/hostapd.log"
sleep 2

# ── 3b. hand out IP addresses ────────────────────────────────────────────────
# hostapd only does the 802.11 half: radio, encryption, authentication. Once a
# client associates it asks for an IP over DHCP — and with nobody answering,
# NetworkManager waits out the DHCP timeout and then fails the connection with
# "IP configuration could not be completed". So the AP needs an address itself
# and a DHCP server behind it. dnsmasq is the smallest thing that does both.
say "Giving $ap an address and starting DHCP…"
ip addr flush dev "$ap" 2>/dev/null || true
ip addr add 10.42.0.1/24 dev "$ap" 2>/dev/null || true
ip link set "$ap" up 2>/dev/null || true

if command -v dnsmasq >/dev/null 2>&1; then
    pkill -f "dnsmasq.*$ap" 2>/dev/null || true
    dnsmasq \
        --interface="$ap" \
        --bind-interfaces \
        --dhcp-range=10.42.0.10,10.42.0.100,12h \
        --dhcp-option=3,10.42.0.1 \
        --dhcp-option=6,10.42.0.1 \
        --pid-file=/tmp/dnsmasq-wifitest.pid \
        >/tmp/dnsmasq.log 2>&1 \
        || die "dnsmasq failed — see /tmp/dnsmasq.log"
    sleep 1
else
    printf '\n\033[1;33m~~ dnsmasq is not installed — the client will associate but get no IP,\n'
    printf '   and NetworkManager will fail with "IP configuration could not be\n'
    printf '   completed". Add dnsmasq to the ISO to test the full flow.\033[0m\n'
fi

# ── 4. report ────────────────────────────────────────────────────────────────
if nmcli -t -f SSID dev wifi list --rescan yes 2>/dev/null | grep -q "^$SSID$"; then
    say "SUCCESS — NetworkManager can see the network."
else
    printf '\n\033[1;33m~~ AP is up, but NM does not list it yet. Give it a few seconds,\n'
    printf '   or press Enter/r on the installer'\''s network screen to rescan.\033[0m\n'
fi

cat <<EOF

  ┌───────────────────────────────────────────────┐
  │  Now go to the installer's Wi-Fi screen:      │
  │                                               │
  │     adapter   →  $sta$(printf '%*s' $((28 - ${#sta})) '')│
  │     network   →  $SSID$(printf '%*s' $((28 - ${#SSID})) '')│
  │     password  →  $PASS$(printf '%*s' $((28 - ${#PASS})) '')│
  └───────────────────────────────────────────────┘

  Worth testing while you're there:
    • a WRONG password  → must stay on the screen with a red error
    • Enter on an empty list → must rescan, never sit silent

EOF
"###;
